services:
  sc13-trace:
    image: zsr12383/sc13-trace:latest
    container_name: sc13-trace
    user: 1000:1000
    volumes:
      - ./.env:/app/.env
      - ./logs/sc13:/app/logs
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
    restart: always
    command: python ./sc13bot.py
  8k-trace:
    image: zsr12383/8k:latest
    container_name: 8k-trace
    user: 1000:1000
    volumes:
      - ./.env:/app/.env
      - ./logs/8k:/app/logs
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
    restart: always
    command: python ./8k.py
  yahoo-trace:
    image: zsr12383/yahoo-bot:latest
    container_name: yahoo-trace
    user: 1000:1000
    volumes:
      - ./.env:/app/.env
      - ./logs/yahoo:/app/logs
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
    restart: always
    command: python ./yahoobot.py
