name: Build and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: zsr12383/sc13-trace:latest

      - name: create env file
        run: |
          touch ./deploy/.env
          echo "${{ secrets.ENV_VARS }}" >> ./deploy/.env

      - name: create remote directory
        uses: appleboy/ssh-action@1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: mkdir -p ~/work/sc13

      - name: copy source via ssh key
        uses: burnett01/rsync-deployments@7.0.1
        with:
          path: ./deploy
          switches: -avzr --delete
          remote_path: ~/work/sc13/
          remote_host: ${{ secrets.HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.KEY }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          envs:
          script: |
            sh ~/work/sc13/docker-install.sh
            echo "start docker-compose up: ubuntu"
            sudo docker-compose -v
            cat ~/work/sc13/.env
            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login --username your_dockerhub_username --password-stdin
            sudo docker-compose -f ~/work/sc13/docker-compose.yml pull
            sudo docker-compose -f ~/work/sc13/docker-compose.yml up -d
            echo "prune images"
            sudo docker system prune --all -f

#      - name: Deploy to EC2
#        env:
#          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#          DOCKERHUB_REPOSITORY: zsr12383/sc13-trace
#          EC2_HOST: ${{ secrets.EC2_HOST }}
#          EC2_USER: ${{ secrets.EC2_USER }}
#          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
#          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
#        run: |
#          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
#          chmod 400 ec2_key.pem
#          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
#            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
#            docker pull zsr12383/sc13-trace:latest
#            docker stop my_container || true
#            docker rm my_container || true
#            echo "${{secrets.ENV_VARS}}" > .env
#            docker run -d --name my_container --env-file .env zsr12383/sc13-trace:${{ steps.get_version.outputs.VERSION }}
#          EOF
